title: "A Website all About Diya!"
description: "Personal Wesbite about Diya Chengappa"

## Background Information

"I am a junior at East Brunswick High School, and I have been living here for my whole life with my parents."

## Social Media

## Accomplishments
1. Almost done with High School
2. Scored over a 750 on my math SAT section
3. idk yet

theme: jekyll-theme-cayman
